### ISSUE TITLE
Request: Create Wiki and Discussions sections in this repo

### ISSUE THREAD

**Issue by ramisedhom** [tot0/ObsidianPPV#10]
@tot0 Would you please create Wiki and Discussions sections in this repo?

I had started a wiki seed in my fork: https://github.com/ramisedhom/ObsidianPPV/wiki but I would prefer to make it here.

Sorry to create this request as an issue as this is the main way to communicate with you currently.

**Comment by tot0** [comment]
Doing this now!

**Comment by tot0** [comment]
Done!

**Comment by ramisedhom** [comment]
@tot0 Would you like to open the wiki for collaboration or how do you suggest to collaborate together in building it?
