### ISSUE TITLE
Removing/Changing "New Action" alias on frontmatter breaks dataviewjs queries 

### ISSUE THREAD

**Issue by jidloyola** [tot0/ObsidianPPV#17]
Additionally, Inside a Project, all TODOs are named New Action even if you already specified a unique name for your TODO.

**Comment by tot0** [comment]
Yea the queries do rely on an alias existing, this logic could be more resilient. Perhaps a function called `getNoteName()` which checks for an alias and if there isn't one it uses frontmatter title/filename/heading 1 if that's easily accessible.

Chaning the default `New Action` alias to something else should work though, I do this for all my tasks.
