### ISSUE TITLE
Button "New Week" in "550 📅 Months" folder note

### ISSUE THREAD

**Issue by ramisedhom** [tot0/ObsidianPPV#8]
In "550 📅 Months" folder note, the button to create new month is actually creating new week:

![image](https://user-images.githubusercontent.com/1517228/157468417-fdb5d86b-f4f9-4f7e-8028-4aee13ab8a39.png)

with following code underneath:
```
```dataviewjs
const {DvActions} = customJS
DvActions.getNewFileButton({
    app,
    dv,
    luxon,
    that:this,
    buttonName:"🗓 New Week",
    folder:"500 ♽ Cycles/530 🗓 Weeks",
    nameFormat:"yyyy'-W'WW",
    split:true
})
```

I think this need to be changed to:

```
```dataviewjs
const {DvActions} = customJS
DvActions.getNewFileButton({
    app,
    dv,
    luxon,
    that:this,
    buttonName:"📅 New Month",
    folder:"500 ♽ Cycles/550 📅 Months",
    nameFormat:"yyyy-MM",
    split:true
})
```

**Comment by tot0** [comment]
Classic copy paste mistake, thanks for putting a fix out. Before I looked at Issues/PRs I merged in some updates as #9 which covers this Issue. Though I will check before I PR next time!
